import Foundation

extension AppStrings {
    static let traditionalChinese = AppStrings(
tagline: "說話 → 理解 → 安排 → 提醒",
        permissionStatus: "權限狀態",
        tasks: "任務",
        today: "今天",
        overdue: "逾期",
        upcoming: "未來",
        doneColumn: "已完成",
        nothingHereYet: "暫無內容",
        permissionsDeniedPrefix: "部分權限被拒绝：",
        openPermissionHint: "打開「權限狀態」以請求權限或在設定中修正。",
        openCommandChat: "打開語音指令",
        newTaskA11y: "新任務",
        homeTab: "首頁",
        calendarTab: "行事曆",
        calendarTitle: "行事曆",
        previousMonth: "上個月",
        nextMonth: "下個月",
        noTasksThisDay: "當天沒有任務",
        commandTitle: "指令",
        dismissDone: "完成",
        titlePlaceholder: "標題",
        notesPlaceholder: "備註",
        date: "日期",
        time: "時間",
        removeDate: "移除日期",
        specificTime: "具體時間",
        none: "無",
        todaySummary: "今天",
        tomorrowSummary: "明天",
        anytime: "隨時",
        newTask: "新任務",
        cancel: "取消",
        add: "添加",
        taskSection: "任務",
        scheduleSection: "日程",
        scheduledToggle: "已计划",
        datePickerLabel: "日期",
        timePickerLabel: "時間",
        scheduleHint: "關閉「具體時間」則該任務在當天為隨時。",
        completed: "已完成",
        deleteTask: "刪除任務",
        markComplete: "標記為完成",
        markIncomplete: "標記為未完成",
        editTaskDetails: "編輯任務詳情",
        permissionsNavigationTitle: "權限",
        permissionsIntro: "ChatTask 需要這些權限以聽取語音、辨識文字、發送提醒並加入行事曆行程。可在設定中更改已拒絕的項目。",
        permissionsStatusHeader: "状態",
        lastMessageHeader: "最近提示",
        settings: "設定",
        requestAccess: "請求授權",
        permissionMicrophone: "麥克風",
        permissionSpeech: "語音辨識",
        permissionNotifications: "通知",
        permissionCalendar: "日曆",
        permissionMicExplanation: "用於聽取語音指令。",
        permissionSpeechExplanation: "用於將語音轉為文字。",
        permissionNotificationsExplanation: "用於在合適時間提醒您。",
        permissionCalendarExplanation: "用於向日曆加入行程。",
        statusNotAsked: "未詢問",
        statusAllowed: "已允許",
        statusDenied: "已拒絕",
        statusRestricted: "受限制",
        statusProvisional: "临時",
        statusUnknown: "未知",
        voiceTapToSpeak: "點擊麥克風開始說話。",
        voiceListening: "正在聆聽… 說完后自动停止，也可隨時點擊停止。",
        voiceProcessing: "處理中…",
        voiceReady: "可以說下一条指令了。",
        voiceError: "出错了，请重試。",
        voiceStartListening: "開始聆聽",
        voiceStopListening: "停止聆聽",
        chatEmptyTranscript: "没聽清，请再說長一點。",
        chatErrorOffline: "您已离線，请检查網絡連接。",
        chatErrorNothingRecorded: "没有聽到聲音，请重試。",
        chatErrorServiceUnavailable: "服務暂時不可用，请稍后重試。",
        chatErrorSomethingWentWrong: "出错了，请重試。",
        chatErrorServiceNotAvailable: "服務目前不可用。",
        chatUnknownSchedule: """
            已保存 %@，但無法從您的話里确定日期或時間。

            请在首頁或行事曆中打開該任務，點進去在编辑器里設置日程（或保留為隨時）。
            """,
        chatTryRemind: "還不太會安排這类說法。試試「提醒我…」或「今天下午 3 點…」。",
        chatReminderMinutes: "好的——%1$d 分鐘后提醒你%2$@。",
        chatReminderMinutesPlural: "好的——%1$d 分鐘后提醒你%2$@。",
        chatReminderHours: "好的——%1$d 小時后提醒你%2$@。",
        chatReminderHoursPlural: "好的——%1$d 小時后提醒你%2$@。",
        chatReminderAt: "好的——我會在 %1$@ 提醒你%2$@。",
        chatReminderAbout: "好的——我會提醒你%@。",
        chatEventAt: "好的——已記下 %1$@，時間 %2$@。",
        chatEventCalendar: "好的——已把 %@ 記在行事曆上。",
        chatAlsoNoted: "另外：%@。",
        chatYourTask: "該任務",
        taskCountOne: "1 個任務",
        taskCountMany: "%d 個任務",
        selected: "已選中",
        permissionMicDeniedAfterRequest: "麥克風權限被拒绝。可在設置中開启。",
        permissionSpeechDeniedAfterRequest: "語音辨識權限被拒绝。可在設置中開启。",
        permissionNotificationsDenied: "未允许通知。可在設置中開启。",
        permissionNotificationsErrorPrefix: "無法请求通知：",
        permissionCalendarDenied: "行事曆權限被拒绝。可在設置中開启。",
        permissionCalendarErrorPrefix: "行事曆錯誤：",
        chatConflictWarning: "註意：你已有「%@」安排在 %@。仍要添加「%@」吗？",
        chatConflictAddAnyway: "仍要添加",
        chatConflictCancel: "不添加",
        chatConflictCanceled: "好的，已取消。",
        chatEditNoTaskFound: "找不到該時間的任務，请說得更精确一些。",
        chatEditAmbiguousTask: "該時間附近有多個任務，请說得更具体一些。",
        chatDisambiguateSelect: "該時間附近有 %d 個任務，是哪一個？",
        chatDeletePrompt: "删除「%@」？",
        chatDeleteConfirm: "删除",
        chatDeleteKeep: "保留",
        chatDeleteSuccess: "已删除「%@」。",
        chatDeleteCanceled: "好的，已保留。",
        chatRescheduleSuccess: "已完成——将「%@」改到 %@。",
        chatAppendSuccess: "已為「%@」添加備註。",
        chatTextInputPlaceholder: "输入或說出任務\u{2026}",
        reminderLabel: "提醒",
        reminderDefaultLabel: "預設提醒時間",
        appLanguage: "應用程式語言",
        settingsNavigationTitle: "設置",
        settingsPermissionsSection: "權限",
        settingsPermissionNotificationsTitle: "通知",
        settingsPermissionMicrophoneTitle: "麥克風",
        settingsPermissionSpeechTitle: "語音辨識",
        settingsPermissionEnabled: "已開啟",
        settingsPermissionDisabled: "未開啟",
        settingsPermissionNotificationsFooter: "用于在约定時間發送提醒。",
        settingsPermissionMicrophoneFooter: "用于語音指令。",
        settingsPermissionSpeechFooter: "用于将語音轉為任務。",
        settingsSectionGeneral: "一般",
        settingsSectionAppearance: "外觀",
        settingsUILanguageFooter: "仅影響界面按钮与菜单，任務内容保持您输入的語言。",
        settingsSectionReminders: "提醒",
        settingsReminderDefaultFooter: "作為新任務与語音指令的預設提前提醒時間。",
        settingsSectionVoice: "語音與輸入",
        settingsSectionSubscription: "訂閱",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "已訂閱",
        settingsSubscriptionStatusNotSubscribed: "未訂閱",
        settingsRestorePurchases: "回復購買",
        settingsSectionSupport: "支援",
        settingsPrivacyPolicy: "隱私權政策",
        settingsTermsOfUse: "使用條款",
        settingsContactSupport: "聯絡支援",
        settingsSectionAbout: "關於",
        settingsVersionLabel: "版本",
        settingsAppRowLabel: "應用程式",
        settingsAlertErrorTitle: "錯誤",
        needsTime: "需要具体時間",
        reminderOffsetAtTime: "准時",
        reminderOffset5Min: "提前 5 分鐘",
        reminderOffset15Min: "提前 15 分鐘",
        reminderOffset30Min: "提前 30 分鐘",
        reminderOffset1Hour: "提前 1 小時",
        paywallTrialHeadline: "開始 5 天免费試用",
        paywallTrialPricingLine: "之后 $2.99/月或 $24.99/年",
        paywallDisclosureLine: "5 天免费試用，之后 $2.99/月或 $24.99/年。",
        paywallAutoRenews: "除非取消，否则自动续订。",
        paywallCancelAnytime: "隨時可取消。",
        paywallRestorePurchases: "回復購買",
        paywallNotNow: "暂不",
        paywallStartTrial: "開始免费試用",
        paywallRestoring: "正在恢复…"
    )
}
