import Foundation

// MARK: - Hindi (full UI parity with English `AppStrings`)

extension AppStrings {
    static let hindi = AppStrings(
        tagline: "बोलें → समझें → निर्धारित करें → याद दिलाएँ",
        permissionStatus: "अनुमति स्थिति",
        tasks: "कार्य",
        today: "आज",
        overdue: "विलंबित",
        upcoming: "आगामी",
        doneColumn: "पूर्ण",
        nothingHereYet: "अभी कुछ नहीं",
        permissionsDeniedPrefix: "कुछ अनुमतियाँ अस्वीकृत हैं:",
        openPermissionHint: "पहुँच माँगने या सेटिंग्स में ठीक करने के लिए अनुमति स्थिति खोलें।",
        openCommandChat: "कमांड चैट खोलें",
        newTaskA11y: "नया कार्य",
        homeTab: "होम",
        calendarTab: "कैलेंडर",
        calendarTitle: "कैलेंडर",
        previousMonth: "पिछला महीना",
        nextMonth: "अगला महीना",
        noTasksThisDay: "इस दिन कोई कार्य नहीं",
        commandTitle: "कमांड",
        dismissDone: "हो गया",
        titlePlaceholder: "शीर्षक",
        notesPlaceholder: "नोट्स",
        date: "तारीख",
        time: "समय",
        removeDate: "तारीख हटाएँ",
        specificTime: "विशिष्ट समय",
        none: "कोई नहीं",
        todaySummary: "आज",
        tomorrowSummary: "कल",
        anytime: "कभी भी",
        newTask: "नया कार्य",
        cancel: "रद्द करें",
        add: "जोड़ें",
        taskSection: "कार्य",
        scheduleSection: "अनुसूची",
        scheduledToggle: "निर्धारित",
        datePickerLabel: "तारीख",
        timePickerLabel: "समय",
        scheduleHint: "उस दिन कार्य को «कभी भी» मानने के लिए «विशिष्ट समय» बंद रखें।",
        completed: "पूर्ण",
        deleteTask: "कार्य हटाएँ",
        markComplete: "पूर्ण चिह्नित करें",
        markIncomplete: "अपूर्ण चिह्नित करें",
        editTaskDetails: "कार्य विवरण संपादित करें",
        permissionsNavigationTitle: "अनुमतियाँ",
        permissionsIntro: "ChatTask को आपकी आवाज़ सुनने, भाषण समझने, अनुस्मारक भेजने और कैलेंडर में घटनाएँ जोड़ने के लिए ये अनुमतियाँ चाहिए। अस्वीकृत वस्तुएँ सेटिंग्स में बदली जा सकती हैं।",
        permissionsStatusHeader: "स्थिति",
        lastMessageHeader: "अंतिम संदेश",
        settings: "सेटिंग्स",
        requestAccess: "पहुँच का अनुरोध करें",
        permissionMicrophone: "माइक्रोफ़ोन",
        permissionSpeech: "वाणी पहचान",
        permissionNotifications: "सूचनाएँ",
        permissionCalendar: "कैलेंडर",
        permissionMicExplanation: "आपकी आवाज़ कमांड सुनने के लिए आवश्यक।",
        permissionSpeechExplanation: "भाषण को पाठ में बदलने के लिए आवश्यक।",
        permissionNotificationsExplanation: "सही समय पर याद दिलाने के लिए आवश्यक।",
        permissionCalendarExplanation: "कैलेंडर में घटनाएँ जोड़ने के लिए आवश्यक।",
        statusNotAsked: "नहीं पूछा गया",
        statusAllowed: "अनुमत",
        statusDenied: "अस्वीकृत",
        statusRestricted: "प्रतिबंधित",
        statusProvisional: "अस्थायी",
        statusUnknown: "अज्ञात",
        voiceTapToSpeak: "बोलने के लिए माइक्रोफ़ोन पर टैप करें।",
        voiceListening: "सुन रहा हूँ… जब आप बोलना समाप्त करेंगे तब रुकूँगा। कभी भी रोकने के लिए टैप करें।",
        voiceProcessing: "प्रोसेसिंग…",
        voiceReady: "आपके अगले कमांड के लिए तैयार।",
        voiceError: "कुछ गलत हुआ — पुनः प्रयास करें।",
        voiceStartListening: "सुनना शुरू करें",
        voiceStopListening: "सुनना बंद करें",
        chatEmptyTranscript: "समझ नहीं पाया। थोड़ा लंबा बोलकर देखें।",
        chatErrorOffline: "आप ऑफ़लाइन हैं। कृपया अपना इंटरनेट कनेक्शन जाँचें।",
        chatErrorNothingRecorded: "कुछ सुनाई नहीं दिया। कृपया पुनः प्रयास करें।",
        chatErrorServiceUnavailable: "सेवा अस्थायी रूप से उपलब्ध नहीं है। कृपया पुनः प्रयास करें।",
        chatErrorSomethingWentWrong: "कुछ गलत हुआ। कृपया पुनः प्रयास करें।",
        chatErrorServiceNotAvailable: "सेवा अभी उपलब्ध नहीं है।",
        chatUnknownSchedule: """
            %@ सहेजा गया, लेकिन आपके शब्दों से तारीख या समय निर्धारित करने में पूर्ण विश्वास नहीं हो सका।

            होम या कैलेंडर से कार्य खोलें, उस पर टैप करें, और संपादक में अनुसूचि सेट करें (या कभी भी छोड़ दें)।
            """,
        chatTryRemind: "अभी यह निर्धारित करना सुनिश्चित नहीं कर सकता। «मुझे याद दिलाएँ…» या «आज दोपहर 3 बजे…» आज़माएँ।",
        chatReminderMinutes: "समझ गया — मैं %1$d मिनट में %2$@ का अनुस्मारक दूँगा।",
        chatReminderMinutesPlural: "समझ गया — मैं %1$d मिनट में %2$@ का अनुस्मारक दूँगा।",
        chatReminderHours: "समझ गया — मैं %1$d घंटे में %2$@ का अनुस्मारक दूँगा।",
        chatReminderHoursPlural: "समझ गया — मैं %1$d घंटों में %2$@ का अनुस्मारक दूँगा।",
        chatReminderAt: "समझ गया — मैं %1$@ को %2$@ का अनुस्मारक दूँगा।",
        chatReminderAbout: "समझ गया — मैं आपको %@ का अनुस्मारक दूँगा।",
        chatEventAt: "समझ गया — मैंने %1$@ को %2$@ के लिए नोट किया।",
        chatEventCalendar: "समझ गया — मैंने %@ को आपके कैलेंडर में जोड़ा।",
        chatAlsoNoted: "यह भी नोट किया: %@।",
        chatYourTask: "आपका कार्य",
        taskCountOne: "1 कार्य",
        taskCountMany: "%d कार्य",
        selected: "चयनित",
        permissionMicDeniedAfterRequest: "माइक्रोफ़ोन पहुँच अस्वीकृत। आप इसे सेटिंग्स में सक्षम कर सकते हैं।",
        permissionSpeechDeniedAfterRequest: "वाणी पहचान अस्वीकृत। आप इसे सेटिंग्स में सक्षम कर सकते हैं।",
        permissionNotificationsDenied: "सूचनाएँ अनुमत नहीं थीं। आप उन्हें सेटिंग्स में सक्षम कर सकते हैं।",
        permissionNotificationsErrorPrefix: "सूचनाएँ अनुरोध नहीं कर सके:",
        permissionCalendarDenied: "कैलेंडर पहुँच अस्वीकृत। आप इसे सेटिंग्स में सक्षम कर सकते हैं।",
        permissionCalendarErrorPrefix: "कैलेंडर त्रुटि:",
        chatConflictWarning: "सूचना — आपके पास पहले से \"%@\" %@ पर है। क्या फिर भी \"%@\" उसी समय जोड़ें?",
        chatConflictAddAnyway: "फिर भी जोड़ें",
        chatConflictCancel: "न जोड़ें",
        chatConflictCanceled: "ठीक है, कार्य सहेजा नहीं गया।",
        chatEditNoTaskFound: "उस समय कोई कार्य नहीं मिला। समय सटीक बताएँ।",
        chatEditAmbiguousTask: "उस समय के आसपास एक से अधिक कार्य मिले। कृपया अधिक स्पष्ट बताएँ।",
        chatDisambiguateSelect: "उस समय %d कार्य मिले — आप किसका मतलब था?",
        chatDeletePrompt: "\"%@\" हटाएँ?",
        chatDeleteConfirm: "हटाएँ",
        chatDeleteKeep: "रखें",
        chatDeleteSuccess: "\"%@\" हटाया गया।",
        chatDeleteCanceled: "ठीक है, रखा गया।",
        chatRescheduleSuccess: "हो गया — \"%@\" को %@ पर ले जाया गया।",
        chatAppendSuccess: "\"%@\" में नोट जोड़ा गया।",
        chatTextInputPlaceholder: "कार्य टाइप करें या बोलें\u{2026}",
        reminderLabel: "अनुस्मारक",
        reminderDefaultLabel: "डिफ़ॉल्ट अनुस्मारक",
        appLanguage: "ऐप भाषा",
        settingsNavigationTitle: "सेटिंग्स",
        settingsPermissionsSection: "अनुमतियाँ",
        settingsPermissionNotificationsTitle: "सूचनाएँ",
        settingsPermissionMicrophoneTitle: "माइक्रोफ़ोन",
        settingsPermissionSpeechTitle: "वाणी पहचान",
        settingsPermissionEnabled: "सक्षम",
        settingsPermissionDisabled: "अक्षम",
        settingsPermissionNotificationsFooter: "समय पर अनुस्मारक भेजने के लिए आवश्यक।",
        settingsPermissionMicrophoneFooter: "आवाज़ कमांड के लिए उपयोग होता है।",
        settingsPermissionSpeechFooter: "आपकी आवाज़ को कार्यों में बदलने के लिए।",
        settingsSectionGeneral: "सामान्य",
        settingsSectionAppearance: "रूप",
        settingsUILanguageFooter: "बटन और मेनू पर लागू होता है। कार्य शीर्षक आप जैसे दर्ज करें वैसे रहते हैं।",
        settingsSectionReminders: "अनुस्मारक",
        settingsReminderDefaultFooter: "नए कार्यों और आवाज़ कमांड के लिए डिफ़ॉल्ट पूर्व सूचना समय।",
        settingsSectionVoice: "वॉइस और इनपुट",
        settingsSectionSubscription: "सदस्यता",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "सक्रिय",
        settingsSubscriptionStatusNotSubscribed: "सदस्यता नहीं",
        settingsRestorePurchases: "खरीदारी पुनर्स्थापित करें",
        settingsSectionSupport: "सहायता",
        settingsPrivacyPolicy: "गोपनीयता नीति",
        settingsTermsOfUse: "उपयोग की शर्तें",
        settingsContactSupport: "सहायता से संपर्क करें",
        settingsSectionAbout: "परिचय",
        settingsVersionLabel: "संस्करण",
        settingsAppRowLabel: "ऐप",
        settingsAlertErrorTitle: "त्रुटि",
        needsTime: "समय चाहिए",
        reminderOffsetAtTime: "समय पर",
        reminderOffset5Min: "5 मिनट पहले",
        reminderOffset15Min: "15 मिनट पहले",
        reminderOffset30Min: "30 मिनट पहले",
        reminderOffset1Hour: "1 घंटा पहले",
        paywallTrialHeadline: "अपना 5-दिन का निःशुल्क परीक्षण शुरू करें",
        paywallTrialPricingLine: "फिर $2.99/माह या $24.99/वर्ष",
        paywallDisclosureLine: "5-दिन का निःशुल्क परीक्षण, फिर $2.99/माह या $24.99/वर्ष।",
        paywallAutoRenews: "रद्द न करने पर स्वतः नवीनीकरण।",
        paywallCancelAnytime: "कभी भी रद्द करें।",
        paywallRestorePurchases: "खरीदारी पुनर्स्थापित करें",
        paywallNotNow: "अभी नहीं",
        paywallStartTrial: "निःशुल्क परीक्षण शुरू करें",
        paywallRestoring: "पुनर्स्थापित कर रहे हैं…"
    )
}
