import Foundation

// MARK: - French, German, Dutch (full UI parity with English `AppStrings`)

extension AppStrings {

    static let french = AppStrings(
        tagline: "Parlez → Comprenez → Planifiez → Rappelez",
        permissionStatus: "État des autorisations",
        tasks: "Tâches",
        today: "Aujourd’hui",
        overdue: "En retard",
        upcoming: "À venir",
        doneColumn: "Terminées",
        nothingHereYet: "Rien pour le moment",
        permissionsDeniedPrefix: "Certaines autorisations sont refusées :",
        openPermissionHint: "Ouvrez État des autorisations pour demander l’accès ou modifiez les réglages dans Réglages.",
        openCommandChat: "Ouvrir le chat de commandes",
        newTaskA11y: "Nouvelle tâche",
        homeTab: "Accueil",
        calendarTab: "Calendrier",
        calendarTitle: "Calendrier",
        previousMonth: "Mois précédent",
        nextMonth: "Mois suivant",
        noTasksThisDay: "Aucune tâche ce jour",
        commandTitle: "Commande",
        dismissDone: "OK",
        titlePlaceholder: "Titre",
        notesPlaceholder: "Notes",
        date: "Date",
        time: "Heure",
        removeDate: "Supprimer la date",
        specificTime: "Heure précise",
        none: "Aucune",
        todaySummary: "Aujourd’hui",
        tomorrowSummary: "Demain",
        anytime: "N’importe quand",
        newTask: "Nouvelle tâche",
        cancel: "Annuler",
        add: "Ajouter",
        taskSection: "Tâche",
        scheduleSection: "Planification",
        scheduledToggle: "Planifiée",
        datePickerLabel: "Date",
        timePickerLabel: "Heure",
        scheduleHint: "Désactivez « Heure précise » pour traiter la tâche comme « N’importe quand » ce jour-là.",
        completed: "Terminée",
        deleteTask: "Supprimer la tâche",
        markComplete: "Marquer comme terminée",
        markIncomplete: "Marquer comme non terminée",
        editTaskDetails: "Modifier la tâche",
        permissionsNavigationTitle: "Autorisations",
        permissionsIntro: "ChatTask a besoin de ces autorisations pour vous entendre, comprendre la parole, envoyer des rappels et ajouter des événements au calendrier. Les éléments refusés peuvent être modifiés dans Réglages.",
        permissionsStatusHeader: "État",
        lastMessageHeader: "Dernier message",
        settings: "Réglages",
        requestAccess: "Demander l’accès",
        permissionMicrophone: "Microphone",
        permissionSpeech: "Reconnaissance vocale",
        permissionNotifications: "Notifications",
        permissionCalendar: "Calendrier",
        permissionMicExplanation: "Nécessaire pour entendre vos commandes vocales.",
        permissionSpeechExplanation: "Nécessaire pour convertir la parole en texte.",
        permissionNotificationsExplanation: "Nécessaire pour vous rappeler au bon moment.",
        permissionCalendarExplanation: "Nécessaire pour ajouter des événements à votre calendrier.",
        statusNotAsked: "Pas encore demandé",
        statusAllowed: "Autorisé",
        statusDenied: "Refusé",
        statusRestricted: "Restreint",
        statusProvisional: "Provisoire",
        statusUnknown: "Inconnu",
        voiceTapToSpeak: "Touchez le microphone pour parler.",
        voiceListening: "Écoute… J’arrêterai quand vous aurez fini de parler. Touchez pour arrêter à tout moment.",
        voiceProcessing: "Traitement…",
        voiceReady: "Prêt pour votre prochaine commande.",
        voiceError: "Un problème est survenu — réessayez.",
        voiceStartListening: "Commencer l’écoute",
        voiceStopListening: "Arrêter l’écoute",
        chatEmptyTranscript: "Je n’ai pas bien entendu. Parlez un peu plus longtemps.",
        chatErrorOffline: "Vous êtes hors ligne. Vérifiez votre connexion Internet.",
        chatErrorNothingRecorded: "Je n’ai rien entendu. Veuillez réessayer.",
        chatErrorServiceUnavailable: "Le service est temporairement indisponible. Veuillez réessayer.",
        chatErrorSomethingWentWrong: "Une erreur s’est produite. Veuillez réessayer.",
        chatErrorServiceNotAvailable: "Le service n’est pas disponible pour le moment.",
        chatUnknownSchedule: """
            J’ai enregistré %@, mais je n’ai pas pu déterminer clairement une date ou une heure à partir de ce que vous avez dit.

            Ouvrez la tâche depuis l’accueil ou le calendrier, touchez-la et définissez la planification dans l’éditeur (ou laissez « N’importe quand »).
            """,
        chatTryRemind: "Je ne sais pas encore planifier cela. Essayez « rappelle-moi… » ou « aujourd’hui à 15 h… ».",
        chatReminderMinutes: "D’accord — je vous rappellerai dans %1$d minute pour %2$@.",
        chatReminderMinutesPlural: "D’accord — je vous rappellerai dans %1$d minutes pour %2$@.",
        chatReminderHours: "D’accord — je vous rappellerai dans %1$d heure pour %2$@.",
        chatReminderHoursPlural: "D’accord — je vous rappellerai dans %1$d heures pour %2$@.",
        chatReminderAt: "D’accord — je vous rappellerai à %1$@ pour %2$@.",
        chatReminderAbout: "D’accord — je vous rappellerai pour %@.",
        chatEventAt: "D’accord — j’ai noté %1$@ pour %2$@.",
        chatEventCalendar: "D’accord — j’ai ajouté %@ à votre calendrier.",
        chatAlsoNoted: "J’ai aussi noté : %@.",
        chatYourTask: "votre tâche",
        taskCountOne: "1 tâche",
        taskCountMany: "%d tâches",
        selected: "sélectionné",
        permissionMicDeniedAfterRequest: "L’accès au microphone a été refusé. Vous pouvez l’activer dans Réglages.",
        permissionSpeechDeniedAfterRequest: "La reconnaissance vocale a été refusée. Vous pouvez l’activer dans Réglages.",
        permissionNotificationsDenied: "Les notifications n’ont pas été autorisées. Vous pouvez les activer dans Réglages.",
        permissionNotificationsErrorPrefix: "Impossible de demander les notifications :",
        permissionCalendarDenied: "L’accès au calendrier a été refusé. Vous pouvez l’activer dans Réglages.",
        permissionCalendarErrorPrefix: "Erreur de calendrier :",
        chatConflictWarning: "Attention — vous avez déjà « %@ » à %@. Ajouter « %@ » au même moment quand même ?",
        chatConflictAddAnyway: "Ajouter quand même",
        chatConflictCancel: "Ne pas ajouter",
        chatConflictCanceled: "D’accord, tâche non enregistrée.",
        chatEditNoTaskFound: "Je n’ai trouvé aucune tâche à ce moment-là. Précisez davantage l’heure.",
        chatEditAmbiguousTask: "Plusieurs tâches correspondent à ce moment. Soyez plus précis.",
        chatDisambiguateSelect: "%d tâches à ce moment — laquelle vouliez-vous dire ?",
        chatDeletePrompt: "Supprimer « %@ » ?",
        chatDeleteConfirm: "Supprimer",
        chatDeleteKeep: "Conserver",
        chatDeleteSuccess: "« %@ » supprimée.",
        chatDeleteCanceled: "D’accord, conservée.",
        chatRescheduleSuccess: "OK — « %@ » déplacée vers %@.",
        chatAppendSuccess: "Note ajoutée à « %@ ».",
        chatTextInputPlaceholder: "Saisissez ou dictez une tâche\u{2026}",
        reminderLabel: "Rappel",
        reminderDefaultLabel: "Rappel par défaut",
        appLanguage: "Langue de l’app",
        settingsNavigationTitle: "Réglages",
        settingsPermissionsSection: "Autorisations",
        settingsPermissionNotificationsTitle: "Notifications",
        settingsPermissionMicrophoneTitle: "Microphone",
        settingsPermissionSpeechTitle: "Reconnaissance vocale",
        settingsPermissionEnabled: "Activé",
        settingsPermissionDisabled: "Désactivé",
        settingsPermissionNotificationsFooter: "Nécessaire pour que les rappels s’affichent à l’heure.",
        settingsPermissionMicrophoneFooter: "Utilisé pour les commandes vocales.",
        settingsPermissionSpeechFooter: "Convertit votre voix en tâches.",
        settingsSectionGeneral: "Général",
        settingsSectionAppearance: "Apparence",
        settingsUILanguageFooter: "S’applique aux boutons et aux menus. Les titres des tâches restent tels que vous les saisissez.",
        settingsSectionReminders: "Rappels",
        settingsReminderDefaultFooter: "Délai par défaut pour les nouvelles tâches et les commandes vocales.",
        settingsSectionVoice: "Voix et saisie",
        settingsSectionSubscription: "Abonnement",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "Actif",
        settingsSubscriptionStatusNotSubscribed: "Non abonné",
        settingsRestorePurchases: "Restaurer les achats",
        settingsSectionSupport: "Assistance",
        settingsPrivacyPolicy: "Politique de confidentialité",
        settingsTermsOfUse: "Conditions d’utilisation",
        settingsContactSupport: "Contacter l’assistance",
        settingsSectionAbout: "À propos",
        settingsVersionLabel: "Version",
        settingsAppRowLabel: "App",
        settingsAlertErrorTitle: "Erreur",
        needsTime: "Heure requise",
        reminderOffsetAtTime: "À l’heure",
        reminderOffset5Min: "5 min avant",
        reminderOffset15Min: "15 min avant",
        reminderOffset30Min: "30 min avant",
        reminderOffset1Hour: "1 h avant",
        paywallTrialHeadline: "Commencez votre essai gratuit de 5 jours",
        paywallTrialPricingLine: "Puis 2,99 $/mois ou 24,99 $/an",
        paywallDisclosureLine: "Essai gratuit de 5 jours, puis 2,99 $/mois ou 24,99 $/an.",
        paywallAutoRenews: "Renouvellement automatique sauf annulation.",
        paywallCancelAnytime: "Annulation possible à tout moment.",
        paywallRestorePurchases: "Restaurer les achats",
        paywallNotNow: "Pas maintenant",
        paywallStartTrial: "Commencer l’essai gratuit",
        paywallRestoring: "Restauration…"
    )

    static let german = AppStrings(
        tagline: "Sprechen → Verstehen → Planen → Erinnern",
        permissionStatus: "Berechtigungsstatus",
        tasks: "Aufgaben",
        today: "Heute",
        overdue: "Überfällig",
        upcoming: "Demnächst",
        doneColumn: "Erledigt",
        nothingHereYet: "Noch nichts hier",
        permissionsDeniedPrefix: "Einige Berechtigungen sind verweigert:",
        openPermissionHint: "Öffnen Sie „Berechtigungsstatus“, um Zugriff anzufragen oder es in den Einstellungen zu ändern.",
        openCommandChat: "Befehls-Chat öffnen",
        newTaskA11y: "Neue Aufgabe",
        homeTab: "Start",
        calendarTab: "Kalender",
        calendarTitle: "Kalender",
        previousMonth: "Vorheriger Monat",
        nextMonth: "Nächster Monat",
        noTasksThisDay: "Keine Aufgaben an diesem Tag",
        commandTitle: "Befehl",
        dismissDone: "Fertig",
        titlePlaceholder: "Titel",
        notesPlaceholder: "Notizen",
        date: "Datum",
        time: "Uhrzeit",
        removeDate: "Datum entfernen",
        specificTime: "Bestimmte Uhrzeit",
        none: "Keine",
        todaySummary: "Heute",
        tomorrowSummary: "Morgen",
        anytime: "Jederzeit",
        newTask: "Neue Aufgabe",
        cancel: "Abbrechen",
        add: "Hinzufügen",
        taskSection: "Aufgabe",
        scheduleSection: "Zeitplan",
        scheduledToggle: "Geplant",
        datePickerLabel: "Datum",
        timePickerLabel: "Uhrzeit",
        scheduleHint: "Schalten Sie „Bestimmte Uhrzeit“ aus, um die Aufgabe an diesem Tag als „Jederzeit“ zu behandeln.",
        completed: "Erledigt",
        deleteTask: "Aufgabe löschen",
        markComplete: "Als erledigt markieren",
        markIncomplete: "Als nicht erledigt markieren",
        editTaskDetails: "Aufgabendetails bearbeiten",
        permissionsNavigationTitle: "Berechtigungen",
        permissionsIntro: "ChatTask benötigt diese Berechtigungen, um Sie zu hören, Sprache zu verstehen, Erinnerungen zu senden und Kalenderereignisse hinzuzufügen. Verweigerte Einträge können in den Einstellungen geändert werden.",
        permissionsStatusHeader: "Status",
        lastMessageHeader: "Letzte Meldung",
        settings: "Einstellungen",
        requestAccess: "Zugriff anfragen",
        permissionMicrophone: "Mikrofon",
        permissionSpeech: "Spracherkennung",
        permissionNotifications: "Mitteilungen",
        permissionCalendar: "Kalender",
        permissionMicExplanation: "Benötigt, um Sprachbefehle zu hören.",
        permissionSpeechExplanation: "Benötigt, um Sprache in Text umzuwandeln.",
        permissionNotificationsExplanation: "Benötigt, um Sie rechtzeitig zu erinnern.",
        permissionCalendarExplanation: "Benötigt, um Ereignisse in Ihrem Kalender hinzuzufügen.",
        statusNotAsked: "Nicht angefragt",
        statusAllowed: "Erlaubt",
        statusDenied: "Verweigert",
        statusRestricted: "Eingeschränkt",
        statusProvisional: "Vorläufig",
        statusUnknown: "Unbekannt",
        voiceTapToSpeak: "Tippen Sie auf das Mikrofon, um zu sprechen.",
        voiceListening: "Hört zu… Ich stoppe, wenn Sie fertig sind. Tippen Sie jederzeit zum Stoppen.",
        voiceProcessing: "Verarbeitung…",
        voiceReady: "Bereit für Ihren nächsten Befehl.",
        voiceError: "Etwas ist schiefgelaufen — bitte erneut versuchen.",
        voiceStartListening: "Zuhören starten",
        voiceStopListening: "Zuhören beenden",
        chatEmptyTranscript: "Das habe ich nicht verstanden. Sprechen Sie etwas länger.",
        chatErrorOffline: "Sie sind offline. Bitte prüfen Sie Ihre Internetverbindung.",
        chatErrorNothingRecorded: "Ich habe nichts gehört. Bitte versuchen Sie es erneut.",
        chatErrorServiceUnavailable: "Der Dienst ist vorübergehend nicht verfügbar. Bitte versuchen Sie es erneut.",
        chatErrorSomethingWentWrong: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
        chatErrorServiceNotAvailable: "Der Dienst ist derzeit nicht verfügbar.",
        chatUnknownSchedule: """
            Ich habe %@ gespeichert, konnte aber kein zuverlässiges Datum oder eine Uhrzeit aus Ihrer Aussage ableiten.

            Öffnen Sie die Aufgabe über Start oder Kalender, tippen Sie darauf und legen Sie den Zeitplan im Editor fest (oder lassen Sie „Jederzeit“).
            """,
        chatTryRemind: "So kann ich das noch nicht planen. Versuchen Sie „Erinnere mich…“ oder „heute um 15 Uhr…“.",
        chatReminderMinutes: "Alles klar — ich erinnere Sie in %1$d Minute an %2$@.",
        chatReminderMinutesPlural: "Alles klar — ich erinnere Sie in %1$d Minuten an %2$@.",
        chatReminderHours: "Alles klar — ich erinnere Sie in %1$d Stunde an %2$@.",
        chatReminderHoursPlural: "Alles klar — ich erinnere Sie in %1$d Stunden an %2$@.",
        chatReminderAt: "Alles klar — ich erinnere Sie um %1$@ an %2$@.",
        chatReminderAbout: "Alles klar — ich erinnere Sie an %@.",
        chatEventAt: "Alles klar — ich habe %1$@ für %2$@ notiert.",
        chatEventCalendar: "Alles klar — ich habe %@ in Ihrem Kalender eingetragen.",
        chatAlsoNoted: "Außerdem notiert: %@.",
        chatYourTask: "Ihre Aufgabe",
        taskCountOne: "1 Aufgabe",
        taskCountMany: "%d Aufgaben",
        selected: "ausgewählt",
        permissionMicDeniedAfterRequest: "Mikrofonzugriff wurde verweigert. Sie können ihn in den Einstellungen aktivieren.",
        permissionSpeechDeniedAfterRequest: "Spracherkennung wurde verweigert. Sie können sie in den Einstellungen aktivieren.",
        permissionNotificationsDenied: "Mitteilungen wurden nicht erlaubt. Sie können sie in den Einstellungen aktivieren.",
        permissionNotificationsErrorPrefix: "Mitteilungen konnten nicht angefordert werden:",
        permissionCalendarDenied: "Kalenderzugriff wurde verweigert. Sie können ihn in den Einstellungen aktivieren.",
        permissionCalendarErrorPrefix: "Kalenderfehler:",
        chatConflictWarning: "Hinweis — Sie haben bereits „%@“ um %@. „%@“ trotzdem zur gleichen Zeit hinzufügen?",
        chatConflictAddAnyway: "Trotzdem hinzufügen",
        chatConflictCancel: "Nicht hinzufügen",
        chatConflictCanceled: "Alles klar, Aufgabe nicht gespeichert.",
        chatEditNoTaskFound: "Ich habe zu dieser Zeit keine Aufgabe gefunden. Nennen Sie die Uhrzeit genauer.",
        chatEditAmbiguousTask: "Ich habe mehrere Aufgaben um diese Zeit gefunden. Bitte präzisieren Sie.",
        chatDisambiguateSelect: "%d Aufgaben zu dieser Zeit — welche meinten Sie?",
        chatDeletePrompt: "„%@“ löschen?",
        chatDeleteConfirm: "Löschen",
        chatDeleteKeep: "Behalten",
        chatDeleteSuccess: "„%@“ gelöscht.",
        chatDeleteCanceled: "OK, behalten.",
        chatRescheduleSuccess: "Erledigt — „%@“ nach %@ verschoben.",
        chatAppendSuccess: "Notiz zu „%@“ hinzugefügt.",
        chatTextInputPlaceholder: "Aufgabe tippen oder sagen\u{2026}",
        reminderLabel: "Erinnerung",
        reminderDefaultLabel: "Standard-Erinnerung",
        appLanguage: "App-Sprache",
        settingsNavigationTitle: "Einstellungen",
        settingsPermissionsSection: "Berechtigungen",
        settingsPermissionNotificationsTitle: "Mitteilungen",
        settingsPermissionMicrophoneTitle: "Mikrofon",
        settingsPermissionSpeechTitle: "Spracherkennung",
        settingsPermissionEnabled: "Aktiviert",
        settingsPermissionDisabled: "Deaktiviert",
        settingsPermissionNotificationsFooter: "Erforderlich, damit Erinnerungen pünktlich erscheinen.",
        settingsPermissionMicrophoneFooter: "Wird für Sprachbefehle verwendet.",
        settingsPermissionSpeechFooter: "Wandelt Ihre Stimme in Aufgaben um.",
        settingsSectionGeneral: "Allgemein",
        settingsSectionAppearance: "Erscheinungsbild",
        settingsUILanguageFooter: "Gilt für Schaltflächen und Menüs. Aufgabentitel bleiben in Ihrer Eingabesprache.",
        settingsSectionReminders: "Erinnerungen",
        settingsReminderDefaultFooter: "Standard-Vorlaufzeit für neue Aufgaben und Sprachbefehle.",
        settingsSectionVoice: "Sprache & Eingabe",
        settingsSectionSubscription: "Abonnement",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "Aktiv",
        settingsSubscriptionStatusNotSubscribed: "Nicht abonniert",
        settingsRestorePurchases: "Käufe wiederherstellen",
        settingsSectionSupport: "Support",
        settingsPrivacyPolicy: "Datenschutzrichtlinie",
        settingsTermsOfUse: "Nutzungsbedingungen",
        settingsContactSupport: "Support kontaktieren",
        settingsSectionAbout: "Info",
        settingsVersionLabel: "Version",
        settingsAppRowLabel: "App",
        settingsAlertErrorTitle: "Fehler",
        needsTime: "Zeit erforderlich",
        reminderOffsetAtTime: "Zur Zeit",
        reminderOffset5Min: "5 Min. vorher",
        reminderOffset15Min: "15 Min. vorher",
        reminderOffset30Min: "30 Min. vorher",
        reminderOffset1Hour: "1 Std. vorher",
        paywallTrialHeadline: "Starten Sie Ihre 5-tägige kostenlose Testversion",
        paywallTrialPricingLine: "Danach 2,99 $/Monat oder 24,99 $/Jahr",
        paywallDisclosureLine: "5-tägige kostenlose Testversion, danach 2,99 $/Monat oder 24,99 $/Jahr.",
        paywallAutoRenews: "Verlängert sich automatisch, sofern nicht gekündigt.",
        paywallCancelAnytime: "Jederzeit kündbar.",
        paywallRestorePurchases: "Käufe wiederherstellen",
        paywallNotNow: "Nicht jetzt",
        paywallStartTrial: "Kostenlose Testversion starten",
        paywallRestoring: "Wiederherstellen…"
    )

    static let dutch = AppStrings(
        tagline: "Spreek → Begrijp → Plan → Herinner",
        permissionStatus: "Machtigingsstatus",
        tasks: "Taken",
        today: "Vandaag",
        overdue: "Achterstallig",
        upcoming: "Binnenkort",
        doneColumn: "Gereed",
        nothingHereYet: "Nog niets hier",
        permissionsDeniedPrefix: "Sommige machtigingen zijn geweigerd:",
        openPermissionHint: "Open Machtigingsstatus om toegang te vragen of dit in Instellingen aan te passen.",
        openCommandChat: "Opdrachtchat openen",
        newTaskA11y: "Nieuwe taak",
        homeTab: "Home",
        calendarTab: "Agenda",
        calendarTitle: "Agenda",
        previousMonth: "Vorige maand",
        nextMonth: "Volgende maand",
        noTasksThisDay: "Geen taken op deze dag",
        commandTitle: "Opdracht",
        dismissDone: "Gereed",
        titlePlaceholder: "Titel",
        notesPlaceholder: "Notities",
        date: "Datum",
        time: "Tijd",
        removeDate: "Datum verwijderen",
        specificTime: "Specifieke tijd",
        none: "Geen",
        todaySummary: "Vandaag",
        tomorrowSummary: "Morgen",
        anytime: "Altijd",
        newTask: "Nieuwe taak",
        cancel: "Annuleer",
        add: "Voeg toe",
        taskSection: "Taak",
        scheduleSection: "Planning",
        scheduledToggle: "Gepland",
        datePickerLabel: "Datum",
        timePickerLabel: "Tijd",
        scheduleHint: "Zet „Specifieke tijd“ uit om de taak die dag als „Altijd“ te behandelen.",
        completed: "Voltooid",
        deleteTask: "Taak verwijderen",
        markComplete: "Markeer als voltooid",
        markIncomplete: "Markeer als niet voltooid",
        editTaskDetails: "Taakdetails bewerken",
        permissionsNavigationTitle: "Machtigingen",
        permissionsIntro: "ChatTask heeft deze machtigingen nodig om u te horen, spraak te begrijpen, herinneringen te sturen en agenda-afspraken toe te voegen. Geweigerde items kunt u in Instellingen wijzigen.",
        permissionsStatusHeader: "Status",
        lastMessageHeader: "Laatste bericht",
        settings: "Instellingen",
        requestAccess: "Toegang vragen",
        permissionMicrophone: "Microfoon",
        permissionSpeech: "Spraakherkenning",
        permissionNotifications: "Meldingen",
        permissionCalendar: "Agenda",
        permissionMicExplanation: "Nodig om uw spraakopdrachten te horen.",
        permissionSpeechExplanation: "Nodig om spraak naar tekst om te zetten.",
        permissionNotificationsExplanation: "Nodig om u op tijd te herinneren.",
        permissionCalendarExplanation: "Nodig om gebeurtenissen aan uw agenda toe te voegen.",
        statusNotAsked: "Niet gevraagd",
        statusAllowed: "Toegestaan",
        statusDenied: "Geweigerd",
        statusRestricted: "Beperkt",
        statusProvisional: "Voorlopig",
        statusUnknown: "Onbekend",
        voiceTapToSpeak: "Tik op de microfoon om te spreken.",
        voiceListening: "Luisteren… Ik stop als u klaar bent met spreken. Tik om op elk moment te stoppen.",
        voiceProcessing: "Verwerken…",
        voiceReady: "Klaar voor uw volgende opdracht.",
        voiceError: "Er ging iets mis — probeer het opnieuw.",
        voiceStartListening: "Begin met luisteren",
        voiceStopListening: "Stop met luisteren",
        chatEmptyTranscript: "Ik heb het niet verstaan. Praat iets langer.",
        chatErrorOffline: "U bent offline. Controleer uw internetverbinding.",
        chatErrorNothingRecorded: "Ik hoorde niets. Probeer het opnieuw.",
        chatErrorServiceUnavailable: "De service is tijdelijk niet beschikbaar. Probeer het opnieuw.",
        chatErrorSomethingWentWrong: "Er ging iets mis. Probeer het opnieuw.",
        chatErrorServiceNotAvailable: "De service is nu niet beschikbaar.",
        chatUnknownSchedule: """
            Ik heb %@ opgeslagen, maar kon geen betrouwbare datum of tijd uit uw woorden afleiden.

            Open de taak via Home of Agenda, tik erop en stel de planning in de editor in (of laat „Altijd“ staan).
            """,
        chatTryRemind: "Ik weet nog niet hoe ik dit moet inplannen. Probeer „herinner me…“ of „vandaag om 15:00…“.",
        chatReminderMinutes: "Oké — ik herinner je over %1$d minuut aan %2$@.",
        chatReminderMinutesPlural: "Oké — ik herinner je over %1$d minuten aan %2$@.",
        chatReminderHours: "Oké — ik herinner je over %1$d uur aan %2$@.",
        chatReminderHoursPlural: "Oké — ik herinner je over %1$d uur aan %2$@.",
        chatReminderAt: "Oké — ik herinner je om %1$@ aan %2$@.",
        chatReminderAbout: "Oké — ik herinner je aan %@.",
        chatEventAt: "Oké — ik heb %1$@ genoteerd voor %2$@.",
        chatEventCalendar: "Oké — ik heb %@ in je agenda gezet.",
        chatAlsoNoted: "Ook genoteerd: %@.",
        chatYourTask: "je taak",
        taskCountOne: "1 taak",
        taskCountMany: "%d taken",
        selected: "geselecteerd",
        permissionMicDeniedAfterRequest: "Microfoontoegang geweigerd. U kunt dit inschakelen in Instellingen.",
        permissionSpeechDeniedAfterRequest: "Spraakherkenning geweigerd. U kunt dit inschakelen in Instellingen.",
        permissionNotificationsDenied: "Meldingen niet toegestaan. U kunt ze inschakelen in Instellingen.",
        permissionNotificationsErrorPrefix: "Kon geen meldingen aanvragen:",
        permissionCalendarDenied: "Agendatoegang geweigerd. U kunt dit inschakelen in Instellingen.",
        permissionCalendarErrorPrefix: "Agendafout:",
        chatConflictWarning: "Let op — u heeft „%@“ al om %@. „%@“ toch tegelijk toevoegen?",
        chatConflictAddAnyway: "Toch toevoegen",
        chatConflictCancel: "Niet toevoegen",
        chatConflictCanceled: "Oké, taak niet opgeslagen.",
        chatEditNoTaskFound: "Ik vond geen taak op dat moment. Zeg de tijd preciezer.",
        chatEditAmbiguousTask: "Ik vond meer dan één taak rond die tijd. Wees specifieker.",
        chatDisambiguateSelect: "%d taken op dat moment — welke bedoelde u?",
        chatDeletePrompt: "„%@“ verwijderen?",
        chatDeleteConfirm: "Verwijder",
        chatDeleteKeep: "Behoud",
        chatDeleteSuccess: "„%@“ verwijderd.",
        chatDeleteCanceled: "Oké, behouden.",
        chatRescheduleSuccess: "Klaar — „%@“ verplaatst naar %@.",
        chatAppendSuccess: "Notitie toegevoegd aan „%@“.",
        chatTextInputPlaceholder: "Typ of zeg een taak\u{2026}",
        reminderLabel: "Herinnering",
        reminderDefaultLabel: "Standaardherinnering",
        appLanguage: "App-taal",
        settingsNavigationTitle: "Instellingen",
        settingsPermissionsSection: "Machtigingen",
        settingsPermissionNotificationsTitle: "Meldingen",
        settingsPermissionMicrophoneTitle: "Microfoon",
        settingsPermissionSpeechTitle: "Spraakherkenning",
        settingsPermissionEnabled: "Ingeschakeld",
        settingsPermissionDisabled: "Uitgeschakeld",
        settingsPermissionNotificationsFooter: "Vereist om herinneringen op tijd te tonen.",
        settingsPermissionMicrophoneFooter: "Gebruikt voor spraakopdrachten.",
        settingsPermissionSpeechFooter: "Zet uw stem om in taken.",
        settingsSectionGeneral: "Algemeen",
        settingsSectionAppearance: "Weergave",
        settingsUILanguageFooter: "Geldt voor knoppen en menu’s. Taaktitels blijven zoals u ze invoert.",
        settingsSectionReminders: "Herinneringen",
        settingsReminderDefaultFooter: "Standaard voorloop voor nieuwe taken en spraakopdrachten.",
        settingsSectionVoice: "Spraak en invoer",
        settingsSectionSubscription: "Abonnement",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "Actief",
        settingsSubscriptionStatusNotSubscribed: "Niet geabonneerd",
        settingsRestorePurchases: "Aankopen herstellen",
        settingsSectionSupport: "Support",
        settingsPrivacyPolicy: "Privacybeleid",
        settingsTermsOfUse: "Gebruiksvoorwaarden",
        settingsContactSupport: "Neem contact op met support",
        settingsSectionAbout: "Over",
        settingsVersionLabel: "Versie",
        settingsAppRowLabel: "App",
        settingsAlertErrorTitle: "Fout",
        needsTime: "Tijd nodig",
        reminderOffsetAtTime: "Op tijd",
        reminderOffset5Min: "5 min ervoor",
        reminderOffset15Min: "15 min ervoor",
        reminderOffset30Min: "30 min ervoor",
        reminderOffset1Hour: "1 u ervoor",
        paywallTrialHeadline: "Start uw gratis proefperiode van 5 dagen",
        paywallTrialPricingLine: "Daarna $2,99/maand of $24,99/jaar",
        paywallDisclosureLine: "5 dagen gratis proefperiode, daarna $2,99/maand of $24,99/jaar.",
        paywallAutoRenews: "Wordt automatisch verlengd tenzij opgezegd.",
        paywallCancelAnytime: "Op elk moment opzegbaar.",
        paywallRestorePurchases: "Aankopen herstellen",
        paywallNotNow: "Niet nu",
        paywallStartTrial: "Gratis proefperiode starten",
        paywallRestoring: "Bezig met herstellen…"
    )
}
