import Foundation

// MARK: - Japanese, Korean, Portuguese (Brazil), Italian

extension AppStrings {

    static let japanese = AppStrings(
        tagline: "話す → 理解 → 予定 → リマインド",
        permissionStatus: "権限の状態",
        tasks: "タスク",
        today: "今日",
        overdue: "期限超過",
        upcoming: "予定",
        doneColumn: "完了",
        nothingHereYet: "まだありません",
        permissionsDeniedPrefix: "一部の権限が拒否されています：",
        openPermissionHint: "「権限の状態」から許可を求めるか、設定で変更してください。",
        openCommandChat: "コマンドチャットを開く",
        newTaskA11y: "新しいタスク",
        homeTab: "ホーム",
        calendarTab: "カレンダー",
        calendarTitle: "カレンダー",
        previousMonth: "前の月",
        nextMonth: "次の月",
        noTasksThisDay: "この日のタスクはありません",
        commandTitle: "コマンド",
        dismissDone: "完了",
        titlePlaceholder: "タイトル",
        notesPlaceholder: "メモ",
        date: "日付",
        time: "時刻",
        removeDate: "日付を削除",
        specificTime: "時刻を指定",
        none: "なし",
        todaySummary: "今日",
        tomorrowSummary: "明日",
        anytime: "いつでも",
        newTask: "新しいタスク",
        cancel: "キャンセル",
        add: "追加",
        taskSection: "タスク",
        scheduleSection: "予定",
        scheduledToggle: "予定あり",
        datePickerLabel: "日付",
        timePickerLabel: "時刻",
        scheduleHint: "「時刻を指定」をオフにすると、その日は「いつでも」として扱います。",
        completed: "完了",
        deleteTask: "タスクを削除",
        markComplete: "完了にする",
        markIncomplete: "未完了にする",
        editTaskDetails: "タスクの詳細を編集",
        permissionsNavigationTitle: "権限",
        permissionsIntro: "ChatTask は、音声を聞き取り、音声をテキストにし、リマインダーを送り、カレンダーに予定を追加するためにこれらの権限が必要です。拒否された項目は設定で変更できます。",
        permissionsStatusHeader: "状態",
        lastMessageHeader: "最後のメッセージ",
        settings: "設定",
        requestAccess: "許可をリクエスト",
        permissionMicrophone: "マイク",
        permissionSpeech: "音声認識",
        permissionNotifications: "通知",
        permissionCalendar: "カレンダー",
        permissionMicExplanation: "音声コマンドを聞くために必要です。",
        permissionSpeechExplanation: "音声をテキストに変換するために必要です。",
        permissionNotificationsExplanation: "適切なタイミングでリマインドするために必要です。",
        permissionCalendarExplanation: "カレンダーに予定を追加するために必要です。",
        statusNotAsked: "未確認",
        statusAllowed: "許可",
        statusDenied: "拒否",
        statusRestricted: "制限",
        statusProvisional: "仮",
        statusUnknown: "不明",
        voiceTapToSpeak: "マイクをタップして話してください。",
        voiceListening: "聞いています… 終わったら停止をタップしてください。",
        voiceProcessing: "処理中…",
        voiceWakingUpServer: "少々お待ちください…",
        chatAssistantThinking: "考え中…",
        voiceReady: "次のコマンドをどうぞ。",
        voiceError: "問題が発生しました。もう一度お試しください。",
        voiceStartListening: "聞き取りを開始",
        voiceStopListening: "聞き取りを停止",
        chatEmptyTranscript: "聞き取れませんでした。もう少し長く話してください。",
        chatErrorOffline: "オフラインです。インターネット接続を確認してください。",
        chatErrorNothingRecorded: "音が聞こえませんでした。もう一度お試しください。",
        chatErrorServiceUnavailable: "サービスが一時的に利用できません。後でもう一度お試しください。",
        chatErrorSomethingWentWrong: "問題が発生しました。もう一度お試しください。",
        chatErrorServiceNotAvailable: "現在サービスを利用できません。",
        chatUnknownSchedule: """
            %@ は保存しましたが、お話から日付や時刻を確実に判断できませんでした。

            ホームまたはカレンダーからタスクを開き、タップしてエディターで予定を設定するか、「いつでも」のままにしてください。
            """,
        chatTryRemind: "まだその予定の取り方が分かりません。「リマインドして…」や「今日の午後3時…」を試してください。",
        chatReminderMinutes: "了解です — %1$d 分後に %2$@ についてお知らせします。",
        chatReminderMinutesPlural: "了解です — %1$d 分後に %2$@ についてお知らせします。",
        chatReminderHours: "了解です — %1$d 時間後に %2$@ についてお知らせします。",
        chatReminderHoursPlural: "了解です — %1$d 時間後に %2$@ についてお知らせします。",
        chatReminderAt: "了解です — %1$@ に %2$@ についてお知らせします。",
        chatReminderAbout: "了解です — %@ についてお知らせします。",
        chatEventAt: "了解です — %2$@ に %1$@ をメモしました。",
        chatEventCalendar: "了解です — %@ をカレンダーに追加しました。",
        chatAlsoNoted: "メモも追加しました：%@。",
        chatYourTask: "このタスク",
        taskCountOne: "タスク 1 件",
        taskCountMany: "タスク %d 件",
        selected: "選択中",
        permissionMicDeniedAfterRequest: "マイクが拒否されました。設定から有効にできます。",
        permissionSpeechDeniedAfterRequest: "音声認識が拒否されました。設定から有効にできます。",
        permissionNotificationsDenied: "通知が許可されませんでした。設定から有効にできます。",
        permissionNotificationsErrorPrefix: "通知をリクエストできませんでした：",
        permissionCalendarDenied: "カレンダーが拒否されました。設定から有効にできます。",
        permissionCalendarErrorPrefix: "カレンダーエラー：",
        chatConflictWarning: "注意 — すでに「%1$@」が %2$@ にあります。「%3$@」を同じ時間に追加しますか？",
        chatConflictAddAnyway: "追加する",
        chatConflictCancel: "追加しない",
        chatConflictCanceled: "了解しました。保存しませんでした。",
        chatEditNoTaskFound: "その時間のタスクが見つかりません。時刻をもっと正確に言ってください。",
        chatEditAmbiguousTask: "その時間付近に複数のタスクがあります。もっと具体的に言ってください。",
        chatDisambiguateSelect: "その時間に %d 件のタスクがあります — どれですか？",
        chatDeletePrompt: "「%@」を削除しますか？",
        chatDeleteConfirm: "削除",
        chatDeleteKeep: "残す",
        chatDeleteSuccess: "「%@」を削除しました。",
        chatDeleteCanceled: "了解しました。残しました。",
        chatRescheduleSuccess: "完了 — 「%@」を %@ に移動しました。",
        chatAppendSuccess: "「%@」にメモを追加しました。",
        chatFollowUpHint: "このタスクの編集を続けられます。",
        chatRenameSuccess: "「%@」に名前を変更しました。",
        chatTextInputPlaceholder: "タスクを入力または話す\u{2026}",
        reminderLabel: "リマインダー",
        reminderDefaultLabel: "デフォルトのリマインダー",
        appLanguage: "アプリの言語",
        settingsNavigationTitle: "設定",
        settingsPermissionsSection: "権限",
        settingsPermissionNotificationsTitle: "通知",
        settingsPermissionMicrophoneTitle: "マイク",
        settingsPermissionSpeechTitle: "音声認識",
        settingsPermissionEnabled: "オン",
        settingsPermissionDisabled: "オフ",
        settingsPermissionNotificationsFooter: "時間どおりにリマインダーを表示するために必要です。",
        settingsPermissionMicrophoneFooter: "音声コマンドに使用します。",
        settingsPermissionSpeechFooter: "声をタスクに変換します。",
        settingsSectionGeneral: "一般",
        settingsSectionAppearance: "外観",
        settingsUILanguageFooter: "ボタンとメニューに適用されます。タスクのタイトルは入力した言語のままです。",
        settingsSectionReminders: "リマインダー",
        settingsReminderDefaultFooter: "新しいタスクと音声コマンドのデフォルトの事前通知です。",
        settingsSectionVoice: "音声と入力",
        settingsSectionSubscription: "サブスクリプション",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "有効",
        settingsSubscriptionStatusNotSubscribed: "未加入",
        settingsRestorePurchases: "購入を復元",
        settingsSectionSupport: "サポート",
        settingsPrivacyPolicy: "プライバシーポリシー",
        settingsTermsOfUse: "利用規約",
        settingsContactSupport: "サポートに連絡",
        settingsSectionAbout: "このアプリについて",
        settingsVersionLabel: "バージョン",
        settingsAppRowLabel: "アプリ",
        settingsAlertErrorTitle: "エラー",
        needsTime: "時刻が必要",
        reminderOffsetAtTime: "定刻",
        reminderOffset5Min: "5 分前",
        reminderOffset15Min: "15 分前",
        reminderOffset30Min: "30 分前",
        reminderOffset1Hour: "1 時間前",
        paywallTrialHeadline: "5 日間の無料トライアルを始める",
        paywallTrialPricingLine: "その後 $2.99/月 または $24.99/年",
        paywallDisclosureLine: "5 日間の無料トライアル、その後 $2.99/月 または $24.99/年。",
        paywallAutoRenews: "解約しない限り自動更新されます。",
        paywallCancelAnytime: "いつでも解約できます。",
        paywallRestorePurchases: "購入を復元",
        paywallNotNow: "後で",
        paywallStartTrial: "無料トライアルを開始",
        paywallRestoring: "復元中…"
    )

    static let korean = AppStrings(
        tagline: "말하기 → 이해 → 일정 → 알림",
        permissionStatus: "권한 상태",
        tasks: "할 일",
        today: "오늘",
        overdue: "기한 지남",
        upcoming: "예정",
        doneColumn: "완료",
        nothingHereYet: "아직 없음",
        permissionsDeniedPrefix: "일부 권한이 거부되었습니다:",
        openPermissionHint: "「권한 상태」를 열어 허용을 요청하거나 설정에서 변경하세요.",
        openCommandChat: "명령 채팅 열기",
        newTaskA11y: "새 할 일",
        homeTab: "홈",
        calendarTab: "캘린더",
        calendarTitle: "캘린더",
        previousMonth: "이전 달",
        nextMonth: "다음 달",
        noTasksThisDay: "이 날 할 일이 없습니다",
        commandTitle: "명령",
        dismissDone: "완료",
        titlePlaceholder: "제목",
        notesPlaceholder: "메모",
        date: "날짜",
        time: "시간",
        removeDate: "날짜 제거",
        specificTime: "시간 지정",
        none: "없음",
        todaySummary: "오늘",
        tomorrowSummary: "내일",
        anytime: "언제든",
        newTask: "새 할 일",
        cancel: "취소",
        add: "추가",
        taskSection: "할 일",
        scheduleSection: "일정",
        scheduledToggle: "예정됨",
        datePickerLabel: "날짜",
        timePickerLabel: "시간",
        scheduleHint: "「시간 지정」을 끄면 그날은 「언제든」으로 처리됩니다.",
        completed: "완료됨",
        deleteTask: "할 일 삭제",
        markComplete: "완료로 표시",
        markIncomplete: "미완료로 표시",
        editTaskDetails: "할 일 세부정보 편집",
        permissionsNavigationTitle: "권한",
        permissionsIntro: "ChatTask는 음성을 듣고, 음성을 텍스트로 바꾸고, 알림을 보내고, 캘린더에 일정을 추가하려면 이러한 권한이 필요합니다. 거부된 항목은 설정에서 변경할 수 있습니다.",
        permissionsStatusHeader: "상태",
        lastMessageHeader: "마지막 메시지",
        settings: "설정",
        requestAccess: "액세스 요청",
        permissionMicrophone: "마이크",
        permissionSpeech: "음성 인식",
        permissionNotifications: "알림",
        permissionCalendar: "캘린더",
        permissionMicExplanation: "음성 명령을 듣기 위해 필요합니다.",
        permissionSpeechExplanation: "음성을 텍스트로 바꾸기 위해 필요합니다.",
        permissionNotificationsExplanation: "제때 알리기 위해 필요합니다.",
        permissionCalendarExplanation: "캘린더에 일정을 추가하기 위해 필요합니다.",
        statusNotAsked: "요청 안 함",
        statusAllowed: "허용",
        statusDenied: "거부",
        statusRestricted: "제한",
        statusProvisional: "임시",
        statusUnknown: "알 수 없음",
        voiceTapToSpeak: "마이크를 탭하여 말하세요.",
        voiceListening: "듣는 중… 끝나면 중지를 탭하세요.",
        voiceProcessing: "처리 중…",
        voiceWakingUpServer: "잠시만요…",
        chatAssistantThinking: "생각 중…",
        voiceReady: "다음 명령을 기다립니다.",
        voiceError: "문제가 발생했습니다. 다시 시도하세요.",
        voiceStartListening: "듣기 시작",
        voiceStopListening: "듣기 중지",
        chatEmptyTranscript: "잘 못 들었습니다. 조금 더 길게 말해 보세요.",
        chatErrorOffline: "오프라인입니다. 인터넷 연결을 확인하세요.",
        chatErrorNothingRecorded: "소리가 들리지 않았습니다. 다시 시도하세요.",
        chatErrorServiceUnavailable: "서비스를 일시적으로 사용할 수 없습니다. 다시 시도하세요.",
        chatErrorSomethingWentWrong: "문제가 발생했습니다. 다시 시도하세요.",
        chatErrorServiceNotAvailable: "지금은 서비스를 사용할 수 없습니다.",
        chatUnknownSchedule: """
            %@(을)를 저장했지만, 말씀에서 날짜나 시간을 확실히 알 수 없었습니다.

            홈 또는 캘린더에서 할 일을 열고 탭한 뒤 편집기에서 일정을 설정하거나 「언제든」으로 두세요.
            """,
        chatTryRemind: "아직 그 일정을 처리하는 법을 잘 모릅니다. 「알려줘…」 또는 「오늘 오후 3시…」를 시도해 보세요.",
        chatReminderMinutes: "알겠습니다 — %1$d분 후 %2$@(을)를 알려드릴게요.",
        chatReminderMinutesPlural: "알겠습니다 — %1$d분 후 %2$@(을)를 알려드릴게요.",
        chatReminderHours: "알겠습니다 — %1$d시간 후 %2$@(을)를 알려드릴게요.",
        chatReminderHoursPlural: "알겠습니다 — %1$d시간 후 %2$@(을)를 알려드릴게요.",
        chatReminderAt: "알겠습니다 — %1$@에 %2$@(을)를 알려드릴게요.",
        chatReminderAbout: "알겠습니다 — %@(을)를 알려드릴게요.",
        chatEventAt: "알겠습니다 — %2$@에 %1$@(을)를 기록했습니다.",
        chatEventCalendar: "알겠습니다 — %@(을) 캘린더에 넣었습니다.",
        chatAlsoNoted: "메모도 남겼습니다: %@.",
        chatYourTask: "할 일",
        taskCountOne: "할 일 1개",
        taskCountMany: "할 일 %d개",
        selected: "선택됨",
        permissionMicDeniedAfterRequest: "마이크가 거부되었습니다. 설정에서 켤 수 있습니다.",
        permissionSpeechDeniedAfterRequest: "음성 인식이 거부되었습니다. 설정에서 켤 수 있습니다.",
        permissionNotificationsDenied: "알림이 허용되지 않았습니다. 설정에서 켤 수 있습니다.",
        permissionNotificationsErrorPrefix: "알림을 요청할 수 없습니다:",
        permissionCalendarDenied: "캘린더가 거부되었습니다. 설정에서 켤 수 있습니다.",
        permissionCalendarErrorPrefix: "캘린더 오류:",
        chatConflictWarning: "알림 — 이미 「%1$@」가 %2$@에 있습니다. 「%3$@」를 같은 시간에 추가할까요?",
        chatConflictAddAnyway: "그래도 추가",
        chatConflictCancel: "추가 안 함",
        chatConflictCanceled: "알겠습니다. 저장하지 않았습니다.",
        chatEditNoTaskFound: "그 시간의 할 일을 찾지 못했습니다. 시간을 더 정확히 말해 주세요.",
        chatEditAmbiguousTask: "그 시간대에 여러 할 일이 있습니다. 더 구체적으로 말해 주세요.",
        chatDisambiguateSelect: "그 시간에 할 일 %d개 — 어느 것인가요?",
        chatDeletePrompt: "「%@」을(를) 삭제할까요?",
        chatDeleteConfirm: "삭제",
        chatDeleteKeep: "유지",
        chatDeleteSuccess: "「%@」을(를) 삭제했습니다.",
        chatDeleteCanceled: "알겠습니다. 유지했습니다.",
        chatRescheduleSuccess: "완료 — 「%@」을(를) %@(으)로 옮겼습니다.",
        chatAppendSuccess: "「%@」에 메모를 추가했습니다.",
        chatFollowUpHint: "이 작업을 계속 편집할 수 있어요.",
        chatRenameSuccess: "이름이 「%@」(으)로 바뀌었습니다.",
        chatTextInputPlaceholder: "할 일을 입력하거나 말하세요\u{2026}",
        reminderLabel: "알림",
        reminderDefaultLabel: "기본 알림",
        appLanguage: "앱 언어",
        settingsNavigationTitle: "설정",
        settingsPermissionsSection: "권한",
        settingsPermissionNotificationsTitle: "알림",
        settingsPermissionMicrophoneTitle: "마이크",
        settingsPermissionSpeechTitle: "음성 인식",
        settingsPermissionEnabled: "켜짐",
        settingsPermissionDisabled: "꺼짐",
        settingsPermissionNotificationsFooter: "제때 알림을 표시하려면 필요합니다.",
        settingsPermissionMicrophoneFooter: "음성 명령에 사용됩니다.",
        settingsPermissionSpeechFooter: "음성을 할 일로 바꿉니다.",
        settingsSectionGeneral: "일반",
        settingsSectionAppearance: "모양",
        settingsUILanguageFooter: "버튼과 메뉴에 적용됩니다. 할 일 제목은 입력한 그대로입니다.",
        settingsSectionReminders: "알림",
        settingsReminderDefaultFooter: "새 할 일과 음성 명령의 기본 미리 알림 시간입니다.",
        settingsSectionVoice: "음성 및 입력",
        settingsSectionSubscription: "구독",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "사용 중",
        settingsSubscriptionStatusNotSubscribed: "미구독",
        settingsRestorePurchases: "구매 복원",
        settingsSectionSupport: "지원",
        settingsPrivacyPolicy: "개인정보 처리방침",
        settingsTermsOfUse: "이용 약관",
        settingsContactSupport: "지원팀에 문의",
        settingsSectionAbout: "정보",
        settingsVersionLabel: "버전",
        settingsAppRowLabel: "앱",
        settingsAlertErrorTitle: "오류",
        needsTime: "시간 필요",
        reminderOffsetAtTime: "정각",
        reminderOffset5Min: "5분 전",
        reminderOffset15Min: "15분 전",
        reminderOffset30Min: "30분 전",
        reminderOffset1Hour: "1시간 전",
        paywallTrialHeadline: "5일 무료 체험 시작",
        paywallTrialPricingLine: "이후 월 $2.99 또는 연 $24.99",
        paywallDisclosureLine: "5일 무료 체험 후 월 $2.99 또는 연 $24.99.",
        paywallAutoRenews: "취소하지 않으면 자동 갱신됩니다.",
        paywallCancelAnytime: "언제든지 취소할 수 있습니다.",
        paywallRestorePurchases: "구매 복원",
        paywallNotNow: "나중에",
        paywallStartTrial: "무료 체험 시작",
        paywallRestoring: "복원 중…"
    )

    static let portugueseBrazil = AppStrings(
        tagline: "Fale → Entenda → Planeje → Lembre",
        permissionStatus: "Status das permissões",
        tasks: "Tarefas",
        today: "Hoje",
        overdue: "Atrasadas",
        upcoming: "Próximas",
        doneColumn: "Concluídas",
        nothingHereYet: "Nada aqui ainda",
        permissionsDeniedPrefix: "Algumas permissões estão negadas:",
        openPermissionHint: "Abra Status das permissões para solicitar acesso ou ajustar em Ajustes.",
        openCommandChat: "Abrir chat de comandos",
        newTaskA11y: "Nova tarefa",
        homeTab: "Início",
        calendarTab: "Calendário",
        calendarTitle: "Calendário",
        previousMonth: "Mês anterior",
        nextMonth: "Próximo mês",
        noTasksThisDay: "Sem tarefas neste dia",
        commandTitle: "Comando",
        dismissDone: "OK",
        titlePlaceholder: "Título",
        notesPlaceholder: "Notas",
        date: "Data",
        time: "Hora",
        removeDate: "Remover data",
        specificTime: "Hora específica",
        none: "Nenhuma",
        todaySummary: "Hoje",
        tomorrowSummary: "Amanhã",
        anytime: "A qualquer hora",
        newTask: "Nova tarefa",
        cancel: "Cancelar",
        add: "Adicionar",
        taskSection: "Tarefa",
        scheduleSection: "Agenda",
        scheduledToggle: "Agendada",
        datePickerLabel: "Data",
        timePickerLabel: "Hora",
        scheduleHint: "Desative «Hora específica» para tratar a tarefa como «A qualquer hora» naquele dia.",
        completed: "Concluída",
        deleteTask: "Excluir tarefa",
        markComplete: "Marcar como concluída",
        markIncomplete: "Marcar como pendente",
        editTaskDetails: "Editar detalhes da tarefa",
        permissionsNavigationTitle: "Permissões",
        permissionsIntro: "O ChatTask precisa dessas permissões para ouvir você, entender a fala, enviar lembretes e adicionar eventos ao calendário. Itens negados podem ser alterados em Ajustes.",
        permissionsStatusHeader: "Status",
        lastMessageHeader: "Última mensagem",
        settings: "Ajustes",
        requestAccess: "Solicitar acesso",
        permissionMicrophone: "Microfone",
        permissionSpeech: "Reconhecimento de fala",
        permissionNotifications: "Notificações",
        permissionCalendar: "Calendário",
        permissionMicExplanation: "Necessário para ouvir seus comandos de voz.",
        permissionSpeechExplanation: "Necessário para converter fala em texto.",
        permissionNotificationsExplanation: "Necessário para lembrá-lo no momento certo.",
        permissionCalendarExplanation: "Necessário para adicionar eventos ao seu calendário.",
        statusNotAsked: "Não solicitado",
        statusAllowed: "Permitido",
        statusDenied: "Negado",
        statusRestricted: "Restrito",
        statusProvisional: "Provisório",
        statusUnknown: "Desconhecido",
        voiceTapToSpeak: "Toque no microfone para falar.",
        voiceListening: "Ouvindo… toque em parar quando terminar.",
        voiceProcessing: "Processando…",
        voiceWakingUpServer: "Só um instante…",
        chatAssistantThinking: "Pensando…",
        voiceReady: "Pronto para o próximo comando.",
        voiceError: "Algo deu errado — tente novamente.",
        voiceStartListening: "Começar a ouvir",
        voiceStopListening: "Parar de ouvir",
        chatEmptyTranscript: "Não entendi bem. Fale um pouco mais.",
        chatErrorOffline: "Você está offline. Verifique sua conexão com a internet.",
        chatErrorNothingRecorded: "Não ouvi nada. Tente novamente.",
        chatErrorServiceUnavailable: "O serviço está temporariamente indisponível. Tente novamente.",
        chatErrorSomethingWentWrong: "Algo deu errado. Tente novamente.",
        chatErrorServiceNotAvailable: "O serviço não está disponível no momento.",
        chatUnknownSchedule: """
            Salvei %@, mas não consegui identificar com confiança uma data ou hora do que você disse.

            Abra a tarefa em Início ou Calendário, toque nela e defina a agenda no editor (ou deixe como «A qualquer hora»).
            """,
        chatTryRemind: "Ainda não sei agendar isso. Tente «lembre-me…» ou «hoje às 15:00…».",
        chatReminderMinutes: "Certo — vou lembrá-lo em %1$d minuto para %2$@.",
        chatReminderMinutesPlural: "Certo — vou lembrá-lo em %1$d minutos para %2$@.",
        chatReminderHours: "Certo — vou lembrá-lo em %1$d hora para %2$@.",
        chatReminderHoursPlural: "Certo — vou lembrá-lo em %1$d horas para %2$@.",
        chatReminderAt: "Certo — vou lembrá-lo às %1$@ para %2$@.",
        chatReminderAbout: "Certo — vou lembrá-lo para %@.",
        chatEventAt: "Certo — anotei %1$@ para %2$@.",
        chatEventCalendar: "Certo — coloquei %@ no seu calendário.",
        chatAlsoNoted: "Também anotei: %@.",
        chatYourTask: "sua tarefa",
        taskCountOne: "1 tarefa",
        taskCountMany: "%d tarefas",
        selected: "selecionado",
        permissionMicDeniedAfterRequest: "O microfone foi negado. Você pode ativar em Ajustes.",
        permissionSpeechDeniedAfterRequest: "O reconhecimento de fala foi negado. Você pode ativar em Ajustes.",
        permissionNotificationsDenied: "As notificações não foram permitidas. Você pode ativar em Ajustes.",
        permissionNotificationsErrorPrefix: "Não foi possível solicitar notificações:",
        permissionCalendarDenied: "O calendário foi negado. Você pode ativar em Ajustes.",
        permissionCalendarErrorPrefix: "Erro de calendário:",
        chatConflictWarning: "Atenção — você já tem «%@» às %@. Adicionar «%@» no mesmo horário mesmo assim?",
        chatConflictAddAnyway: "Adicionar assim mesmo",
        chatConflictCancel: "Não adicionar",
        chatConflictCanceled: "Ok, tarefa não salva.",
        chatEditNoTaskFound: "Não encontrei uma tarefa nesse horário. Diga o horário com mais precisão.",
        chatEditAmbiguousTask: "Há mais de uma tarefa perto desse horário. Seja mais específico.",
        chatDisambiguateSelect: "%d tarefas nesse horário — qual delas?",
        chatDeletePrompt: "Excluir «%@»?",
        chatDeleteConfirm: "Excluir",
        chatDeleteKeep: "Manter",
        chatDeleteSuccess: "«%@» excluída.",
        chatDeleteCanceled: "Ok, mantida.",
        chatRescheduleSuccess: "Pronto — movi «%@» para %@.",
        chatAppendSuccess: "Nota adicionada a «%@».",
        chatFollowUpHint: "Você pode continuar editando esta tarefa.",
        chatRenameSuccess: "Renomeado para «%@».",
        chatTextInputPlaceholder: "Digite ou diga uma tarefa\u{2026}",
        reminderLabel: "Lembrete",
        reminderDefaultLabel: "Lembrete padrão",
        appLanguage: "Idioma do app",
        settingsNavigationTitle: "Ajustes",
        settingsPermissionsSection: "Permissões",
        settingsPermissionNotificationsTitle: "Notificações",
        settingsPermissionMicrophoneTitle: "Microfone",
        settingsPermissionSpeechTitle: "Reconhecimento de fala",
        settingsPermissionEnabled: "Ativado",
        settingsPermissionDisabled: "Desativado",
        settingsPermissionNotificationsFooter: "Necessário para lembretes no horário certo.",
        settingsPermissionMicrophoneFooter: "Usado para comandos de voz.",
        settingsPermissionSpeechFooter: "Converte sua voz em tarefas.",
        settingsSectionGeneral: "Geral",
        settingsSectionAppearance: "Aparência",
        settingsUILanguageFooter: "Afeta botões e menus. Os títulos das tarefas permanecem como você os digitou.",
        settingsSectionReminders: "Lembretes",
        settingsReminderDefaultFooter: "Antecedência padrão para novas tarefas e comandos de voz.",
        settingsSectionVoice: "Voz e entrada",
        settingsSectionSubscription: "Assinatura",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "Ativo",
        settingsSubscriptionStatusNotSubscribed: "Não assinado",
        settingsRestorePurchases: "Restaurar compras",
        settingsSectionSupport: "Suporte",
        settingsPrivacyPolicy: "Política de privacidade",
        settingsTermsOfUse: "Termos de uso",
        settingsContactSupport: "Contatar suporte",
        settingsSectionAbout: "Sobre",
        settingsVersionLabel: "Versão",
        settingsAppRowLabel: "App",
        settingsAlertErrorTitle: "Erro",
        needsTime: "Precisa de horário",
        reminderOffsetAtTime: "Na hora",
        reminderOffset5Min: "5 min antes",
        reminderOffset15Min: "15 min antes",
        reminderOffset30Min: "30 min antes",
        reminderOffset1Hour: "1 h antes",
        paywallTrialHeadline: "Comece seu teste gratuito de 5 dias",
        paywallTrialPricingLine: "Depois US$ 2,99/mês ou US$ 24,99/ano",
        paywallDisclosureLine: "Teste gratuito de 5 dias, depois US$ 2,99/mês ou US$ 24,99/ano.",
        paywallAutoRenews: "Renova automaticamente, salvo cancelamento.",
        paywallCancelAnytime: "Cancele quando quiser.",
        paywallRestorePurchases: "Restaurar compras",
        paywallNotNow: "Agora não",
        paywallStartTrial: "Iniciar teste gratuito",
        paywallRestoring: "Restaurando…"
    )

    static let italian = AppStrings(
        tagline: "Parla → Comprendi → Pianifica → Ricorda",
        permissionStatus: "Stato autorizzazioni",
        tasks: "Attività",
        today: "Oggi",
        overdue: "In ritardo",
        upcoming: "In arrivo",
        doneColumn: "Completate",
        nothingHereYet: "Ancora niente qui",
        permissionsDeniedPrefix: "Alcune autorizzazioni sono negate:",
        openPermissionHint: "Apri Stato autorizzazioni per richiedere l’accesso o modificarlo in Impostazioni.",
        openCommandChat: "Apri chat comandi",
        newTaskA11y: "Nuova attività",
        homeTab: "Home",
        calendarTab: "Calendario",
        calendarTitle: "Calendario",
        previousMonth: "Mese precedente",
        nextMonth: "Mese successivo",
        noTasksThisDay: "Nessuna attività in questo giorno",
        commandTitle: "Comando",
        dismissDone: "Fine",
        titlePlaceholder: "Titolo",
        notesPlaceholder: "Note",
        date: "Data",
        time: "Ora",
        removeDate: "Rimuovi data",
        specificTime: "Ora specifica",
        none: "Nessuna",
        todaySummary: "Oggi",
        tomorrowSummary: "Domani",
        anytime: "In qualsiasi momento",
        newTask: "Nuova attività",
        cancel: "Annulla",
        add: "Aggiungi",
        taskSection: "Attività",
        scheduleSection: "Pianificazione",
        scheduledToggle: "Pianificata",
        datePickerLabel: "Data",
        timePickerLabel: "Ora",
        scheduleHint: "Disattiva «Ora specifica» per trattare l’attività come «In qualsiasi momento» in quel giorno.",
        completed: "Completata",
        deleteTask: "Elimina attività",
        markComplete: "Segna come completata",
        markIncomplete: "Segna come non completata",
        editTaskDetails: "Modifica dettagli attività",
        permissionsNavigationTitle: "Autorizzazioni",
        permissionsIntro: "ChatTask ha bisogno di queste autorizzazioni per ascoltarti, capire la voce, inviare promemoria e aggiungere eventi al calendario. Gli elementi negati si possono modificare in Impostazioni.",
        permissionsStatusHeader: "Stato",
        lastMessageHeader: "Ultimo messaggio",
        settings: "Impostazioni",
        requestAccess: "Richiedi accesso",
        permissionMicrophone: "Microfono",
        permissionSpeech: "Riconoscimento vocale",
        permissionNotifications: "Notifiche",
        permissionCalendar: "Calendario",
        permissionMicExplanation: "Serve per ascoltare i comandi vocali.",
        permissionSpeechExplanation: "Serve per convertire la voce in testo.",
        permissionNotificationsExplanation: "Serve per ricordarti al momento giusto.",
        permissionCalendarExplanation: "Serve per aggiungere eventi al calendario.",
        statusNotAsked: "Non richiesto",
        statusAllowed: "Consentito",
        statusDenied: "Negato",
        statusRestricted: "Limitato",
        statusProvisional: "Provvisorio",
        statusUnknown: "Sconosciuto",
        voiceTapToSpeak: "Tocca il microfono per parlare.",
        voiceListening: "In ascolto… tocca stop quando hai finito.",
        voiceProcessing: "Elaborazione…",
        voiceWakingUpServer: "Un attimo…",
        chatAssistantThinking: "Sto pensando…",
        voiceReady: "Pronto per il prossimo comando.",
        voiceError: "Qualcosa è andato storto — riprova.",
        voiceStartListening: "Inizia ad ascoltare",
        voiceStopListening: "Interrompi ascolto",
        chatEmptyTranscript: "Non ho capito bene. Parla un po’ più a lungo.",
        chatErrorOffline: "Sei offline. Controlla la connessione a Internet.",
        chatErrorNothingRecorded: "Non ho sentito nulla. Riprova.",
        chatErrorServiceUnavailable: "Il servizio è temporaneamente non disponibile. Riprova.",
        chatErrorSomethingWentWrong: "Qualcosa è andato storto. Riprova.",
        chatErrorServiceNotAvailable: "Il servizio non è disponibile in questo momento.",
        chatUnknownSchedule: """
            Ho salvato %@, ma non sono riuscito a capire con sicurezza una data o un’ora da ciò che hai detto.

            Apri l’attività da Home o Calendario, toccala e imposta la pianificazione nell’editor (o lascia «In qualsiasi momento»).
            """,
        chatTryRemind: "Non so ancora come pianificarlo. Prova «ricordami…» o «oggi alle 15:00…».",
        chatReminderMinutes: "Ok — ti ricorderò tra %1$d minuto per %2$@.",
        chatReminderMinutesPlural: "Ok — ti ricorderò tra %1$d minuti per %2$@.",
        chatReminderHours: "Ok — ti ricorderò tra %1$d ora per %2$@.",
        chatReminderHoursPlural: "Ok — ti ricorderò tra %1$d ore per %2$@.",
        chatReminderAt: "Ok — ti ricorderò alle %1$@ per %2$@.",
        chatReminderAbout: "Ok — ti ricorderò per %@.",
        chatEventAt: "Ok — ho annotato %1$@ per %2$@.",
        chatEventCalendar: "Ok — ho messo %@ sul tuo calendario.",
        chatAlsoNoted: "Ho anche annotato: %@.",
        chatYourTask: "la tua attività",
        taskCountOne: "1 attività",
        taskCountMany: "%d attività",
        selected: "selezionato",
        permissionMicDeniedAfterRequest: "Accesso al microfono negato. Puoi abilitarlo in Impostazioni.",
        permissionSpeechDeniedAfterRequest: "Riconoscimento vocale negato. Puoi abilitarlo in Impostazioni.",
        permissionNotificationsDenied: "Notifiche non consentite. Puoi abilitarle in Impostazioni.",
        permissionNotificationsErrorPrefix: "Impossibile richiedere le notifiche:",
        permissionCalendarDenied: "Accesso al calendario negato. Puoi abilitarlo in Impostazioni.",
        permissionCalendarErrorPrefix: "Errore calendario:",
        chatConflictWarning: "Attenzione — hai già «%@» alle %@. Aggiungere «%@» alla stessa ora comunque?",
        chatConflictAddAnyway: "Aggiungi comunque",
        chatConflictCancel: "Non aggiungere",
        chatConflictCanceled: "Ok, attività non salvata.",
        chatEditNoTaskFound: "Non ho trovato un’attività a quell’ora. Indica l’ora più precisamente.",
        chatEditAmbiguousTask: "Ho trovato più attività vicino a quell’ora. Sii più specifico.",
        chatDisambiguateSelect: "%d attività a quell’ora — quale intendevi?",
        chatDeletePrompt: "Eliminare «%@»?",
        chatDeleteConfirm: "Elimina",
        chatDeleteKeep: "Mantieni",
        chatDeleteSuccess: "«%@» eliminata.",
        chatDeleteCanceled: "Ok, mantenuta.",
        chatRescheduleSuccess: "Fatto — ho spostato «%@» a %@.",
        chatAppendSuccess: "Nota aggiunta a «%@».",
        chatFollowUpHint: "Puoi continuare a modificare questa attività.",
        chatRenameSuccess: "Rinominato in «%@».",
        chatTextInputPlaceholder: "Digita o detta un’attività\u{2026}",
        reminderLabel: "Promemoria",
        reminderDefaultLabel: "Promemoria predefinito",
        appLanguage: "Lingua dell’app",
        settingsNavigationTitle: "Impostazioni",
        settingsPermissionsSection: "Autorizzazioni",
        settingsPermissionNotificationsTitle: "Notifiche",
        settingsPermissionMicrophoneTitle: "Microfono",
        settingsPermissionSpeechTitle: "Riconoscimento vocale",
        settingsPermissionEnabled: "Attivato",
        settingsPermissionDisabled: "Disattivato",
        settingsPermissionNotificationsFooter: "Necessario per ricevere promemoria in orario.",
        settingsPermissionMicrophoneFooter: "Usato per i comandi vocali.",
        settingsPermissionSpeechFooter: "Converte la voce in attività.",
        settingsSectionGeneral: "Generale",
        settingsSectionAppearance: "Aspetto",
        settingsUILanguageFooter: "Si applica a pulsanti e menu. I titoli delle attività restano come li inserisci.",
        settingsSectionReminders: "Promemoria",
        settingsReminderDefaultFooter: "Anticipo predefinito per nuove attività e comandi vocali.",
        settingsSectionVoice: "Voce e input",
        settingsSectionSubscription: "Abbonamento",
        settingsSubscriptionTitle: "ChatTask Pro",
        settingsSubscriptionStatusActive: "Attivo",
        settingsSubscriptionStatusNotSubscribed: "Non abbonato",
        settingsRestorePurchases: "Ripristina acquisti",
        settingsSectionSupport: "Supporto",
        settingsPrivacyPolicy: "Informativa sulla privacy",
        settingsTermsOfUse: "Termini di utilizzo",
        settingsContactSupport: "Contatta il supporto",
        settingsSectionAbout: "Info",
        settingsVersionLabel: "Versione",
        settingsAppRowLabel: "App",
        settingsAlertErrorTitle: "Errore",
        needsTime: "Serve l’ora",
        reminderOffsetAtTime: "All’ora",
        reminderOffset5Min: "5 min prima",
        reminderOffset15Min: "15 min prima",
        reminderOffset30Min: "30 min prima",
        reminderOffset1Hour: "1 h prima",
        paywallTrialHeadline: "Inizia la prova gratuita di 5 giorni",
        paywallTrialPricingLine: "Poi $2,99/mese o $24,99/anno",
        paywallDisclosureLine: "Prova gratuita di 5 giorni, poi $2,99/mese o $24,99/anno.",
        paywallAutoRenews: "Si rinnova automaticamente salvo annullamento.",
        paywallCancelAnytime: "Annulla quando vuoi.",
        paywallRestorePurchases: "Ripristina acquisti",
        paywallNotNow: "Non ora",
        paywallStartTrial: "Inizia prova gratuita",
        paywallRestoring: "Ripristino…"
    )
}
